//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "collections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub edition_id: i32,
    pub fee_receiver: String,
    pub owner: String,
    pub creator: String,
    pub uri: String,
    pub description: String,
    pub image_uri: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mints::Entity")]
    Mints,
}

impl Related<super::mints::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mints.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
